### ISSUE TITLE
Probleme to add custom render parameter

### ISSUE THREAD

**Issue by djayandka** [schroef/Save-Render-Presets#1]
Hello,

I use MacOs Monterey 12.0.1 with Blender 3.3.1 (3.3.1 2022-10-05)
I can't add custom preset, I have this message :
![Capture d’écran 2022-11-04 à 21 10 43](https://user-images.githubusercontent.com/117482626/200065734-c2caae9d-cc1e-4692-baaf-ec0e8bd3c34e.png)

Thanks

**Comment by schroef** [comment]
Will fix that, i believe its needs to be updated with more descriptive attributes in the funcion call.

**Comment by schroef** [comment]
Should be fixed with this release [v0.0.5](https://github.com/schroef/Save-Render-Presets/releases/tag/v0.0.5#:~:text=2%20minutes%20ago-,v0.0.5,-edfa4f8)
